name = "storefront"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "bun install && bun run build && bun run pages:build"

[vars]
NEXT_PUBLIC_API_BASE_URL = "https://ec-api.ertiach.workers.dev"
